CLASS zcl_add_n_to_id DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_amdp_marker_hdb.

    CLASS-METHODS execute FOR SCALAR FUNCTION zfx_add_n_to_id.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ADD_N_TO_ID IMPLEMENTATION.


  METHOD execute BY DATABASE FUNCTION
  FOR HDB LANGUAGE SQLSCRIPT
  OPTIONS READ-ONLY.

    result = parameter1_name + parameter2_name;

  ENDMETHOD.
ENDCLASS.
